pipeline:
  build:
    image: ruby
    commands:
      - gem install bundler
      - bundle install
      - bundle exec jekyll build
  netlify:
    image: lucap/drone-netlify
    token:
      from_secret: netlify_token
    site_id:
      from_secret: website_id
    site_name:
      from_secret: website_name
    path: _site/
