# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "How On Switch"
description: "How does a game run on the Nintendo Switch?"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://switch.pixelateddeveloper.com/" # the base hostname & protocol for your site
enforce_ssl: pixelateddeveloper.com
github_username:  PixelatedDeveloper

# Build settings
markdown: kramdown
