# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: What spec on Switch?
email: info@michaelboumann.info
description: > # this means to ignore newlines until "baseurl:"
  What resolution and fps does this game run at on Switch?!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.michaelboumann.info/switch/" # the base hostname & protocol for your site
enforce_ssl: michaelboumann.info
twitter_username: boumannm
github_username:  boumannm

# Build settings
markdown: kramdown
